stages:
  - build
  - deploy

image: node:latest

build:
  stage: build
  script:
    - cp -rf public/* docs/
    - npm install
    - npx browserslist@latest --update-db
    - npm run build
  only:
    - main
  artifacts:
    paths:
      - docs/
    expire_in: 1 days
    when: always

deploy:
  stage: deploy
  needs:
    - job: build
      artifacts: true
  script:
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$PROD_SSH_PRIVATE_KEY")
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - ssh -t coreit@dataviz-mark16.vital-it.ch "rm -r /var/vhosts/sib.swiss/dataviz-mark16/htdocs/*"
    - scp -r docs/* coreit@dataviz-mark16.vital-it.ch://var/vhosts/sib.swiss/dataviz-mark16/htdocs
  only:
    - main
  when: manual
